# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: FAIR-EASE Pilot name
logo: logo.png
author: ""
copyright: ""

# Auto-exclude files not in the toc
only_build_toc_files        : false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: docs.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://binder.pangeo.io"

# Source dode repository
repository:
  url: https://github.com/fair-ease/doc-jupyterbook-template  # Online location of your docs
  path_to_book: docs  # Optional path to your docs, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# Advanced rendering options
html:
  favicon: https://fairease.eu//themes/fairease/favicon.ico
  use_repository_button: true
  extra_footer: |
    <p>Funded by <a href="https://fairease.eu/">FAIR-EASE</a> and 
    distributed under <a href="https://spdx.org/licenses/CC-BY-4.0.html">CC-BY V4.0</a></p>
